name: Run Vinted Bot

on:
  schedule:
    - cron: "*/1 * * * *"  # Toutes les 1 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Run bot
        run: python vinted_bot.py
