name: Run Vinted Bot

on:
  schedule:
    - cron: "*/15 * * * *"  # Toutes les 15 minutes
  workflow_dispatch:        # Lancement manuel possible

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4
        
      - name: Run bot
        run: python vinted_bot.py
